---
name: Build and upload

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    name: Windwos build
    runs-on: windows-2022
    steps:
    - name: Checkout Repository
      uses: actions/checkout
    - name: cat
      run: cat holepunch.cpp
