---
name: Build and upload

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    name: Ubuntu build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build project
      run: |
          mkdir out
          g++ -o out/holepunch-ubuntu holepunch.cpp

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: holepunch
        path: |
          out/holepunch-ubuntu
